version: '3.3'

services:
  nginx:
    container_name: cont_nginx
    #путь к dockerfile
    build: 
      "./docker/nginx"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./src:/etc/nginx/html:ro"
      - "./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro"
      # подменяем на самоподписанные сертификаты 
      - "./docker/nginx/ssl:/etc/nginx/ssl"
    depends_on:
      - "go-web-app"
    
  go-web-app:
    container_name: cont_go_app
    #путь к main.go и dockerfile
    build: 
      context:  "./"
    volumes:
      - ./cmd/main/images:/go/src/my_app_in_wm/images/:z
    ports:
      - "8080"
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: cont_pg_db
    image: postgres:14.3
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/:z 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
      #PGDATA: ./postgres_data
    ports:
      - "5432:5432"
    
  pg_admin:
    container_name: cont_pg_admin
    image: dpage/pgadmin4:2022-05-31-1
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "127.0.0.1:5050:80"
  #redis:
    #image: redis:3.2-alpine
    #volumes:
    #  - redis_data:/data


