version: '3.3'

services:
  nginx:
    container_name: cont_nginx
    #путь к dockerfile
    build: "./docker/nginx"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./src:/etc/nginx/html:ro"
      - "./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro"
      # подменяем на самоподписанные сертификаты 
      - "./docker/nginx/ssl:/etc/nginx/ssl"
    depends_on:
      - "go-web-app"
  go-web-app:
    container_name: cont_go_app
    #путь к main.go и dockerfile
    build: 
      context:  "./cmd/main"
    ports:
      - "8080"


