version: '3.3'

services:
  nginx:
    container_name: cont_nginx
    #путь к dockerfile
    build: "./docker/nginx"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - "./src:/etc/nginx/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - "go-web-app"
  go-web-app:
    container_name: cont_go_app
    #путь к main.go и dockerfile
    build: "./cmd/main"
    ports:
      - "8081"

    